import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/Components/Header'
import Providers from '@/Components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/e61d350a25.js" crossOrigin="anonymous" defer></script>
      </head>
      <Providers>
        <body className={`${inter.className} main-scroll py-5 px-5 flex flex-col gap-5`}>
          <Header />
          <main className='w-full min-h-[65vh]'>
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
